// Shared data for Military Things To Do — Naval Station Norfolk
// Loaded by norfolk.html (listings) and listing.html (detail pages, ?base=norfolk)
//
// NOTE: this base is a work in progress. Started with a first researched batch
// of restaurants; more categories to follow. Coordinates for this first batch
// were estimated from known downtown Norfolk / Ghent neighborhood landmarks
// rather than a precise per-address geocode — reasonably accurate for
// distance sorting, but worth spot-checking against a mapping tool over time.

const places = [
  // Restaurants & Cafés
  { id:"no-frill-bar-and-grill", name:"No Frill Bar and Grill", cat:"restaurant", dist:7.86, lat:36.877, lng:-76.296, addr:"806 Spotswood Ave, Norfolk", blurb:"A Ghent neighborhood institution for over 20 years — comfort food classics like meatloaf and Sunday brunch, in a colorful, casual setting with a loyal following.", hours:"Mon,Sun 11–20 · Tue–Sat 11–21", phone:"+1 757-627-4262", rating:4.6, reviewCount:1135 },
  { id:"freemason-abbey", name:"Freemason Abbey Restaurant & Tavern", cat:"restaurant", dist:11.15, lat:36.8477, lng:-76.2907, addr:"209 W Freemason St, Norfolk", blurb:"A local favorite for over 30 years, set inside a genuinely striking 148-year-old renovated church downtown — fresh seafood, steaks, and an award-winning she-crab soup, elegant but not stuffy.", hours:"Mon–Sat 11:00–21:00 · Sun 10:00–20:00", phone:"+1 757-622-3966", rating:4.6, reviewCount:1011 },
  { id:"vang-go-bistro", name:"Vang Go Bistro", cat:"restaurant", dist:7.98, lat:36.876, lng:-76.295, addr:"915 W 21st St Ste A, Norfolk", blurb:"A passion-project Asian fusion spot in Ghent from a restaurant-industry veteran — dumplings in chili oil, spicy peanut noodles, and a rotating \"Kitchen Experiment\" dish not on the regular menu.", hours:"Mon–Thu,Sun 11:00–22:00 · Fri/Sat 11:00–23:00", phone:"+1 757-233-8933", rating:4.7, reviewCount:97 },
  { id:"momo-kitchen-norfolk", name:"MOMO Kitchen", cat:"restaurant", dist:6.68, lat:36.887, lng:-76.303, addr:"2401 Hampton Blvd Ste 103, Norfolk", blurb:"Authentic Nepalese cuisine right along Hampton Blvd — genuinely distinctive among Norfolk's dining options, with the momo dumplings the dish is named for.", hours:"Tue–Sat 11:00–21:00 · Closed Mon", phone:"+1 757-335-4949", rating:4.5, reviewCount:34 },
  { id:"gershwins-norfolk", name:"Gershwin's", cat:"restaurant", dist:11.22, lat:36.847, lng:-76.291, addr:"332 Granby St, Norfolk", blurb:"An American bistro and bar downtown with a lounge feel — dinner and late-night drinks through the week, plus a Sunday brunch.", hours:"Tue–Thu,Sun 17:00–23:00 · Fri/Sat 17:00–24:00 · Sun brunch 10:00–14:00", phone:"+1 757-226-0814", rating:4.0, reviewCount:0 },
  { id:"the-stockpot-norfolk", name:"The Stockpot Norfolk", cat:"restaurant", dist:11.22, lat:36.847, lng:-76.291, addr:"215 E Plume St Ste 100, Norfolk", blurb:"A healthy comfort-food cafe downtown — soups, bone broths, salads, and smoothies, with Wednesday Ramen Night a genuine local favorite.", hours:"Mon 7:00–18:00 · Tue,Thu,Fri 7:00–15:00 · Wed 7:00–21:00 · Sat/Sun 8:00–16:00", phone:"+1 757-227-3337", rating:4.5, reviewCount:363 },
  { id:"codex-norfolk", name:"Codex", cat:"restaurant", dist:11.22, lat:36.847, lng:-76.291, addr:"429 Granby St, Norfolk", blurb:"A modern American farm-to-table restaurant with a resolutely casual vibe despite the upscale food — rare and hard-to-find beers and wines, curated cocktails, in a cozy converted 1920s building.", hours:"Mon–Thu 17:00–21:00 · Fri/Sat 17:00–22:00 · Closed Sun", phone:null, rating:4.8, reviewCount:178 },
  { id:"508-locals", name:"508 Locals", cat:"restaurant", dist:10.32, lat:36.855, lng:-76.293, addr:"508 Orapax St, Norfolk", blurb:"A locally owned spot from three friends who wanted craft cocktails, elevated food, and a laid-back vibe all in one place — genuinely good for a date night, with a no-fee private dining room for group events.", hours:"Tue–Thu 11:00–22:00 · Fri 11:00–23:00 · Sat/Sun 16:00–23:00 · Closed Mon", phone:"+1 757-917-5086", rating:4.4, reviewCount:35 },
  { id:"doumars-cones-bbq", name:"Doumar's Cones and BBQ", cat:"restaurant", dist:8.34, lat:36.876, lng:-76.279, addr:"1919 Monticello Ave, Norfolk", blurb:"Genuinely historic: this is where Abe Doumar invented the ice cream cone in 1904, and the same four-iron waffle cone machine from 1905 still rolls cones out front. A 1950s carhop diner serving BBQ and ice cream since 1934.", hours:"Mon–Thu 8:00–23:00 · Fri/Sat 8:00–00:30 · Closed Sun", phone:"+1 757-627-4163", rating:4.5, reviewCount:0 },
  { id:"todd-jurichs-bistro", name:"Todd Jurich's Bistro", cat:"restaurant", dist:11.22, lat:36.847, lng:-76.291, addr:"150 W Main St Ste 100, Norfolk", blurb:"An award-winning upscale bistro downtown that's been a local favorite for over 30 years — five-star New American cuisine and world-class wines from self-taught chef Todd Jurich, in a relaxed rather than stuffy setting.", hours:"Mon–Thu 16:00–21:00 · Fri/Sat 16:00–22:00 · Closed Sun", phone:"+1 757-622-3210", rating:4.2, reviewCount:212 },
  { id:"zekes-nfk", name:"Zeke's NFK", cat:"restaurant", dist:11.02, lat:36.849, lng:-76.290, addr:"800 Granby St, Norfolk", blurb:"A beloved neighborhood café in the Neon District — quality coffee and tea alongside made-to-order poke and açaí bowls, with rotating local artist displays as part of a First Friday series.", hours:"Daily 10:00–20:00", phone:"+1 757-963-5220", rating:4.5, reviewCount:296 },
  { id:"nawab-indian-cuisine", name:"Nawab Indian Cuisine", cat:"restaurant", dist:9.94, lat:36.885, lng:-76.229, addr:"888 N Military Hwy, Norfolk", blurb:"A genuine local icon for over 22 years — tandoori specialties, butter chicken, and a lunch buffet, widely regarded as the best Indian food in the area.", hours:"Mon–Thu 11:30–14:30 & 17:00–22:00 · Fri 11:30–14:30 & 17:00–22:30 · Sat 12:00–15:00 & 17:00–22:30 · Sun 12:00–15:00 & 17:00–22:00", phone:null, rating:4.4, reviewCount:283 },
  { id:"colley-cantina", name:"Colley Cantina", cat:"restaurant", dist:8.00, lat:36.876, lng:-76.294, addr:"1316 Colley Ave, Norfolk", blurb:"A lively Baja-Mexican cantina right on Colley Ave — $5 margaritas, Taco Tuesday specials, karaoke nights, and a patio that's genuinely one of Ghent's most popular hangouts.", hours:"Mon–Thu 16:00–00:00 · Fri/Sat 11:00–02:00 · Sun 11:00–00:00", phone:"+1 757-622-0033", rating:4.2, reviewCount:248 },
  { id:"chick-fil-a-northampton", name:"Chick-fil-A (Northampton Blvd)", cat:"restaurant", dist:8.44, lat:36.900, lng:-76.235, addr:"1501 Premium Outlets Blvd, Norfolk", blurb:"A dependable, family-friendly fast food stop — the Chicken Sandwich, waffle fries, and genuinely fast, polite service, closed Sundays as always.", hours:"Mon–Sat 6:00–22:00 · Closed Sun", phone:"+1 757-500-4405", rating:4.3, reviewCount:0 },
  { id:"saltine-norfolk", name:"Saltine", cat:"restaurant", dist:11.22, lat:36.847, lng:-76.291, addr:"100 E Main St, Norfolk", blurb:"An award-winning modern seafood restaurant on the street level of the Hilton Norfolk The Main — a genuinely great raw bar with fresh-shucked oysters, plus she-crab soup that locals rave about.", hours:"Mon–Thu 11:30–23:00 · Fri 11:30–00:00 · Sat 10:00–00:00 · Sun 10:00–23:00", phone:"+1 757-763-6280", rating:4.5, reviewCount:927 },
  { id:"fair-grounds-coffee", name:"Fair Grounds Coffee Cafe", cat:"restaurant", dist:7.87, lat:36.877, lng:-76.295, addr:"806 Baldwin Ave #2, Norfolk", blurb:"Norfolk's oldest independent coffee shop, tucked into a quirky two-story house in Ghent — great espresso, in-house sandwiches, and a genuinely cozy place to sit a while.", hours:"Mon–Thu,Sun 7–20 · Fri/Sat 7–21", phone:"+1 757-640-2899", rating:4.6, reviewCount:369 },
  { id:"redwood-smoke-shack-norfolk", name:"Redwood Smoke Shack", cat:"restaurant", dist:8.01, lat:36.876, lng:-76.293, addr:"2001 Manteo St, Norfolk", blurb:"Texas-style BBQ smoked low and slow over oak, hickory, and pecan — genuinely great brisket, and one of the only spots in Hampton Roads pouring Texas' own Big Red soda.", hours:"Tue–Sat 11–20 · Closed Sun/Mon", phone:"+1 757-624-1000", rating:4.7, reviewCount:433 },

  // Grocery & Food Stores
  { id:"harris-teeter-ghent", name:"Harris Teeter (Ghent Square)", cat:"grocery", dist:8.00, lat:36.876, lng:-76.294, addr:"1320 Colonial Ave, Norfolk", blurb:"A large, well-stocked two-story Harris Teeter in Ghent Square — genuinely excellent meat and seafood counter, though it gets crowded on weekend mornings and Monday evenings.", hours:"Daily 6:00–23:00", phone:"+1 757-533-9284", rating:4.3, reviewCount:2385 },
  { id:"norfolk-navsta-commissary", name:"Naval Station Norfolk Commissary", cat:"grocery", dist:0.20, lat:36.947, lng:-76.312, addr:"1588 Mall Dr, Naval Station Norfolk", blurb:"The on-base commissary — a full grocery selection at commissary pricing, plus a deli, bakery, rotisserie chicken, and early-bird hours before regular opening.", hours:"Mon,Tue,Wed,Fri,Sat,Sun 9:00–19:00 · Thu 9:00–20:00", phone:"+1 757-423-6070", rating:4.0, reviewCount:15 },
  { id:"food-lion-military-hwy", name:"Food Lion (N Military Hwy)", cat:"grocery", dist:7.19, lat:36.917, lng:-76.238, addr:"1235 N Military Hwy, Norfolk", blurb:"A reliable, no-frills grocery stop with everyday low prices — good for a full grocery run without the crowds of the bigger Harris Teeter locations.", hours:"Daily 7:00–22:00", phone:"+1 757-461-2533", rating:3.7, reviewCount:0 },
  { id:"walmart-neighborhood-market-little-creek", name:"Walmart Neighborhood Market", cat:"grocery", dist:6.75, lat:36.918, lng:-76.243, addr:"1720 E Little Creek Rd, Norfolk", blurb:"A smaller-format Walmart focused on groceries and pharmacy — genuinely useful for a quick, budget-friendly grocery run without navigating a full Supercenter.", hours:"Daily 6:00–23:00", phone:"+1 757-480-0654", rating:3.6, reviewCount:0 },
  { id:"trader-joes-virginia-beach", name:"Trader Joe's (Virginia Beach)", cat:"grocery", dist:28.39, lat:36.838, lng:-76.021, addr:"503 Hilltop Plaza, Virginia Beach", blurb:"The closest Trader Joe's to the base — genuinely worth the drive for the specialty items, wine selection, and famously friendly checkout staff.", hours:"Daily 8:00–21:00", phone:"+1 757-422-4840", rating:4.5, reviewCount:0 },
  { id:"kroger-virginia-beach-blvd", name:"Kroger (Virginia Beach Blvd)", cat:"grocery", dist:25.14, lat:36.838, lng:-76.062, addr:"3330 Virginia Beach Blvd, Virginia Beach", blurb:"A full-size Kroger with a wide selection of fresh produce, meats, and a pharmacy — genuinely reliable for a complete grocery run.", hours:"Mon–Fri 6:00–23:00", phone:"+1 757-486-0040", rating:3.9, reviewCount:0 },
  { id:"aldi-ghent", name:"ALDI (Ghent)", cat:"grocery", dist:8.00, lat:36.876, lng:-76.294, addr:"730 W 21st St, Norfolk", blurb:"A genuinely great budget grocery stop — quality produce, meat, and private-label goods at everyday-low prices, right in Ghent. Bring a quarter for the cart.", hours:"Daily 8:00–20:00", phone:"+1 855-955-2534", rating:3.9, reviewCount:0 },

  // Auto & Transportation
  { id:"mwr-nex-auto-center", name:"MWR/NEX Auto Center", cat:"auto", dist:0.21, lat:36.945, lng:-76.309, addr:"1st Ave & W D St, Bldg U-126, Naval Station Norfolk", blurb:"The on-base auto center — state inspections, tires, and routine maintenance without leaving the installation, run through the Navy Exchange.", hours:"Mon–Fri 10:00–18:00", phone:"+1 757-444-1130", rating:3.6, reviewCount:0 },
  { id:"bingo-tire-auto-service", name:"Bingo Tire & Auto Service", cat:"auto", dist:4.33, lat:36.912, lng:-76.288, addr:"7718 Granby St, Norfolk", blurb:"A full-service shop handling brakes, batteries, alignments, and inspections — convenient for Ghent, Ocean View, and Naval Station Norfolk drivers alike.", hours:"Mon–Fri 8:00–18:00 · Sat 8:00–16:00 · Closed Sun", phone:"+1 757-583-0008", rating:4.4, reviewCount:210 },
  { id:"jiffy-lube-little-creek", name:"Jiffy Lube (E Little Creek Rd)", cat:"auto", dist:6.75, lat:36.918, lng:-76.243, addr:"2463 E Little Creek Rd, Norfolk", blurb:"Fast, no-appointment oil changes, brakes, and battery service — offers a discount for active military, and typically has you in and out in 15 minutes.", hours:"Mon–Fri 8:00–18:00 · Sat 8:00–17:00 · Sun 10:00–16:00", phone:"+1 757-583-4064", rating:4.1, reviewCount:66 },
  { id:"meineke-church-st", name:"Meineke Car Care Center", cat:"auto", dist:10.16, lat:36.858, lng:-76.283, addr:"2610 Church St, Norfolk", blurb:"A full-service repair shop covering oil changes, brakes, mufflers, and AC — a good option when a problem is more than Jiffy Lube's quick-service model can handle.", hours:"Mon–Fri 8:00–18:00 · Sat 8:00–16:00 · Closed Sun", phone:"+1 757-264-6315", rating:4.0, reviewCount:0 },
  { id:"firestone-military-hwy", name:"Firestone Complete Auto Care (N Military Hwy)", cat:"auto", dist:9.94, lat:36.885, lng:-76.229, addr:"800 N Military Hwy, Norfolk", blurb:"A full-service auto shop operating since 1926 — tires, brakes, batteries, and complete vehicle inspections, with extended weekday hours.", hours:"Mon–Fri 7:00–19:00 · Sat 7:00–18:00 · Sun 9:00–17:00", phone:"+1 757-461-2156", rating:3.9, reviewCount:0 },

  // Health & Personal Care
  { id:"naval-medical-center-portsmouth", name:"Naval Medical Center Portsmouth", cat:"health", dist:11.05, lat:36.84750, lng:-76.30472, addr:"620 John Paul Jones Cir, Portsmouth", blurb:"The Navy's oldest continuously operating hospital and the primary TRICARE medical center serving Naval Station Norfolk — a full-service military hospital, open around the clock.", hours:"Open 24 hours", phone:"+1 757-953-5000", rating:3.8, reviewCount:77 },
  { id:"sentara-norfolk-general", name:"Sentara Norfolk General Hospital", cat:"health", dist:9.53, lat:36.8612583, lng:-76.30355, addr:"600 Gresham Dr, Norfolk", blurb:"Hampton Roads' only Level I trauma center and the region's major teaching hospital — the go-to for serious emergencies not handled at a base clinic.", hours:"Open 24 hours", phone:null, rating:3.4, reviewCount:0 },
  { id:"cvs-pharmacy-va-beach-blvd", name:"CVS Pharmacy (E Virginia Beach Blvd)", cat:"health", dist:15.19, lat:36.858, lng:-76.180, addr:"6678 E Virginia Beach Blvd, Norfolk", blurb:"A standard CVS with pharmacy, MinuteClinic walk-in care for minor illnesses and vaccinations, plus the usual first-aid and over-the-counter essentials.", hours:"Daily 8:00–22:00", phone:"+1 757-466-3670", rating:3.5, reviewCount:0 },
  { id:"pearle-vision-wards-corner", name:"Pearle Vision (Wards Corner)", cat:"health", dist:6.36, lat:36.912, lng:-76.253, addr:"128 E Little Creek Rd, Norfolk", blurb:"A locally owned vision care center — eye exams from the independent optometrist next door, plus a wide selection of frames from major brands.", hours:"Mon–Fri 9:00–18:00 · Sat 9:00–14:00 · Closed Sun", phone:null, rating:4.1, reviewCount:0 },
  { id:"walgreens-ghent", name:"Walgreens (Ghent)", cat:"health", dist:8.00, lat:36.876, lng:-76.294, addr:"810 W 21st St, Norfolk", blurb:"A 24-hour-friendly neighborhood pharmacy with vaccinations, health and beauty products, and photo services — a genuinely reliable stop for prescriptions and everyday essentials.", hours:"Daily 7:00–22:00", phone:"+1 757-623-7213", rating:3.9, reviewCount:49 },
  { id:"sentara-urgent-care-wards-corner", name:"Sentara Urgent Care (Wards Corner)", cat:"health", dist:6.36, lat:36.912, lng:-76.253, addr:"7435 Granby St, Norfolk", blurb:"Walk-in urgent care for illnesses and injuries that can't wait for a regular appointment but aren't ER-level — genuinely useful detail: it's a VA-authorized provider for enrolled veterans, plus offers physicals and lab work.", hours:"Daily 8:00–20:00", phone:null, rating:3.9, reviewCount:0 },
  { id:"afc-urgent-care-norfolk", name:"AFC Urgent Care Norfolk", cat:"health", dist:9.94, lat:36.885, lng:-76.229, addr:"1119 N Military Hwy Suite 300, Norfolk", blurb:"Another solid walk-in urgent care option along Military Highway — X-rays and lab work on-site, no appointment needed for minor illnesses and injuries.", hours:"Mon–Fri 8:00–20:00 · Sat/Sun 8:00–17:00", phone:"+1 757-240-3500", rating:3.8, reviewCount:0 },

  // Banking & Financial Services
  { id:"navy-federal-hampton-blvd", name:"Navy Federal Credit Union (Hampton Blvd)", cat:"banking", dist:6.66, lat:36.887, lng:-76.305, addr:"7979 Hampton Blvd, Norfolk", blurb:"The credit union built specifically for military families — this branch sits right along Hampton Blvd near the base, though expect a wait on paydays and Saturdays.", hours:"Mon–Fri 9:00–19:30 · Sat 9:00–13:00 · Closed Sun", phone:"+1 888-842-6328", rating:3.2, reviewCount:17 },
  { id:"townebank-ghent", name:"TowneBank (Ghent)", cat:"banking", dist:8.00, lat:36.876, lng:-76.294, addr:"1006 Colley Ave, Norfolk", blurb:"A well-regarded regional bank with a genuinely personal touch — full-service branch with a drive-up ATM, in the heart of Ghent.", hours:"Mon–Thu 9:00–17:00 · Fri 9:00–18:00 · Closed Sat/Sun", phone:"+1 757-673-1900", rating:4.5, reviewCount:0 },
  { id:"wells-fargo-ghent", name:"Wells Fargo (Ghent)", cat:"banking", dist:8.00, lat:36.876, lng:-76.294, addr:"2000 Colonial Ave, Norfolk", blurb:"A full-service Wells Fargo branch that's served the Ghent area for decades — standard banking services plus a full ATM.", hours:"Mon–Fri 9:00–17:00 · Closed Sat/Sun", phone:"+1 757-314-1701", rating:3.0, reviewCount:0 },
  { id:"chase-bank-ghent", name:"Chase Bank (Ghent)", cat:"banking", dist:8.00, lat:36.876, lng:-76.294, addr:"777 W 21st St, Norfolk", blurb:"A full-service Chase branch in Ghent — checking, savings, and an ATM, with the backing of one of the largest banks in the country.", hours:"Mon–Fri 9:00–17:00 · Sat 9:00–14:00 · Closed Sun", phone:"+1 757-216-0016", rating:3.4, reviewCount:0 },
  { id:"bank-of-america-ghent", name:"Bank of America (Ghent)", cat:"banking", dist:8.00, lat:36.876, lng:-76.294, addr:"1916 Colonial Ave, Norfolk", blurb:"A full-service financial center with a drive-thru ATM — standard checking, savings, and financial planning consultations by appointment.", hours:"Mon–Fri 9:00–17:00 · Closed Sat/Sun", phone:null, rating:3.2, reviewCount:0 },

  // Housing & Off-Base Living
  { id:"gates-of-west-bay", name:"Gates of West Bay Apartments", cat:"housing", dist:2.90, lat:36.9502, lng:-76.2775, addr:"272 W Bay Ave, Norfolk", blurb:"A pet-friendly apartment community in West Ocean View, just a couple blocks from the base gates — 1-3 bedroom units with a pool, sundeck, and recently renovated units.", hours:"Mon–Fri 9:00–17:00 · Closed Sat/Sun", phone:"+1 757-378-0771", rating:3.9, reviewCount:0 },
  { id:"larchmont-apartments", name:"Larchmont Apartments", cat:"housing", dist:7.41, lat:36.898, lng:-76.253, addr:"5504 Monroe Pl, Norfolk", blurb:"A well-regarded community on 9 acres in one of Norfolk's most established neighborhoods — spacious floor plans, minutes from Old Dominion University, Ghent, and the base.", hours:"Mon–Fri 9:00–17:00 · Closed Sat/Sun", phone:"+1 757-489-8929", rating:4.0, reviewCount:0 },
  { id:"roebuck-lofts", name:"The Roebuck Lofts", cat:"housing", dist:11.20, lat:36.847, lng:-76.293, addr:"519 Front St, Norfolk", blurb:"A genuinely striking waterfront loft community in a reimagined 1916 building — studios, one-, and two-bedroom units with a rooftop deck and a private floating dock on the Elizabeth River.", hours:"Leasing office: Mon–Fri 9:00–17:00", phone:"+1 757-955-0650", rating:3.9, reviewCount:0 },

  // Schools & Childcare
  { id:"ghent-school", name:"Ghent School", cat:"schools", dist:8.00, lat:36.876, lng:-76.294, addr:"200 Shirley Ave, Norfolk", blurb:"A well-regarded K-8 public school in Ghent with a Gifted & Talented program — part of Norfolk Public Schools, which serves the base and has multiple schools with the Virginia Purple Star military-friendly designation.", hours:"Mon–Fri 7:30–15:30", phone:"+1 757-628-2565", rating:4.2, reviewCount:0 },
  { id:"maury-high-school", name:"Matthew Fontaine Maury High School", cat:"schools", dist:8.00, lat:36.876, lng:-76.294, addr:"322 Shirley Ave, Norfolk", blurb:"A large, long-established Norfolk Public Schools high school right in Ghent — one of the district's 5 comprehensive high schools serving the base community.", hours:"Mon–Fri 7:30–14:30", phone:null, rating:3.6, reviewCount:0 },
  { id:"larchmont-elementary", name:"Larchmont Elementary School", cat:"schools", dist:7.41, lat:36.898, lng:-76.253, addr:"1145 Bolling Ave, Norfolk", blurb:"A highly-rated public elementary school with a Gifted & Talented program — genuinely useful detail for military families: it offers a Child Military and Family Life Counselor on-site.", hours:"Office 8:00–16:00 · Student hours 8:55–15:15", phone:"+1 757-451-4180", rating:4.2, reviewCount:0 },
  { id:"booker-t-washington-hs", name:"Booker T. Washington High School", cat:"schools", dist:10.16, lat:36.858, lng:-76.283, addr:"1111 Park Ave, Norfolk", blurb:"A genuinely historic school — Virginia's first accredited public high school for African-Americans, founded in 1911. Now known as the Academy of Visual and Performing Arts.", hours:"Office 7:00–15:00 · Student hours 7:25–14:05", phone:null, rating:3.8, reviewCount:0 },

  // Fitness
  { id:"n24-gym", name:"N-24 Gym (Naval Station Norfolk)", cat:"fitness", dist:0.11, lat:36.947, lng:-76.311, addr:"Gilbert St, Bldg N-24, Naval Station Norfolk", blurb:"The main on-base fitness center — free for active duty, with cardio equipment, weights, and group classes just steps from the gate.", hours:"Contact for hours", phone:"+1 757-444-2276", rating:3.8, reviewCount:0 },
  { id:"onelife-fitness-norfolk", name:"Onelife Fitness Norfolk", cat:"fitness", dist:7.84, lat:36.877, lng:-76.297, addr:"1900 Monticello Ave, Norfolk", blurb:"A large, full-amenity gym with a pool, group classes, kids club, and a women's-only workout area — a step up from a basic gym if you want the extras.", hours:"Mon–Thu 5:00–23:00 · Fri 5:00–22:00 · Sat/Sun 7:00–20:00", phone:"+1 757-248-4800", rating:4.1, reviewCount:241 },
  { id:"planet-fitness-military-hwy", name:"Planet Fitness (N Military Hwy)", cat:"fitness", dist:9.94, lat:36.885, lng:-76.229, addr:"415 N Military Hwy, Norfolk", blurb:"A genuinely low-cost, no-pressure \"Judgement Free Zone\" gym open around the clock — good if you want a straightforward place to work out without a big membership commitment.", hours:"Open 24 hours", phone:"+1 757-330-5339", rating:4.2, reviewCount:0 },
  { id:"anytime-fitness-w20th", name:"Anytime Fitness (W 20th St)", cat:"fitness", dist:11.20, lat:36.847, lng:-76.293, addr:"780 W 20th St, Norfolk", blurb:"A clean, well-organized 24/7 gym with separate rooms for different workout styles — genuinely good for avoiding the overcrowding of bigger gyms.", hours:"Open 24 hours", phone:"+1 757-965-2348", rating:4.3, reviewCount:21 },

  // Pet Services
  { id:"ghent-veterinary-hospital", name:"Ghent Veterinary Hospital", cat:"pets", dist:8.09, lat:36.875, lng:-76.295, addr:"939 W 21st St, Norfolk", blurb:"An AAHA-accredited small animal hospital with a genuinely low-stress, fear-free approach — routine care, surgery, dentistry, and in-house diagnostics.", hours:"Mon,Wed,Thu,Fri 8:00–17:00 · Tue 8:00–19:00 · Sat 9:00–14:00 · Closed Sun", phone:"+1 757-351-0167", rating:4.7, reviewCount:41 },
  { id:"banfield-pet-hospital-norfolk", name:"Banfield Pet Hospital", cat:"pets", dist:9.94, lat:36.885, lng:-76.229, addr:"1275 N Military Hwy, Norfolk", blurb:"A full-service vet hospital inside PetSmart — routine vaccinations, dental, surgery, and Optimum Wellness Plans that bundle a year of preventive care.", hours:"Mon–Sat 8:00–18:00 · Sun 9:00–17:00", phone:"+1 757-459-8094", rating:3.4, reviewCount:0 },
  { id:"petsmart-norfolk", name:"PetSmart", cat:"pets", dist:9.94, lat:36.885, lng:-76.229, addr:"1275 N Military Hwy, Norfolk", blurb:"The world's largest pet supply retailer — food, supplies, and accessories for every kind of pet, plus in-store grooming, training classes, and adoption events.", hours:"Mon–Sat 9:00–21:00 · Sun 10:00–19:00", phone:"+1 757-459-6712", rating:4.0, reviewCount:0 },

  // Museums & Attractions
  { id:"nauticus", name:"Nauticus", cat:"museum", dist:11.24, lat:36.8468, lng:-76.2915, addr:"1 Waterside Dr, Norfolk", blurb:"A maritime-themed science center on the downtown waterfront, home to the Battleship Wisconsin — hands-on exhibits covering the region's naval and maritime history, genuinely great for kids.", hours:"Mon–Sat 9:00–17:00 · Sun 10:00–17:00", phone:"+1 757-664-1000", rating:4.5, reviewCount:0 },
  { id:"hampton-roads-naval-museum", name:"Hampton Roads Naval Museum", cat:"museum", dist:11.24, lat:36.8468, lng:-76.2915, addr:"1 Waterside Dr (inside Nauticus), Norfolk", blurb:"A free, AAM-accredited Navy museum covering over 235 years of naval history in Hampton Roads — ask at the Nauticus entrance to be directed up to the second floor.", hours:"Tue–Sat 10:00–17:00 · Sun 12:00–17:00 · Closed Mon", phone:"+1 757-322-3108", rating:4.6, reviewCount:0 },
  { id:"chrysler-museum-of-art", name:"Chrysler Museum of Art", cat:"museum", dist:10.11, lat:36.857, lng:-76.292, addr:"1 Memorial Pl, Norfolk", blurb:"One of America's top mid-sized art museums, with free admission every day — over 30,000 objects including one of the country's great glass collections, plus a working glass studio with live demos.", hours:"Tue–Sat 10:00–17:00 · Sun 12:00–17:00 · Closed Mon", phone:"+1 757-664-6200", rating:4.8, reviewCount:0 },

  // Beaches
  { id:"virginia-beach-boardwalk", name:"Virginia Beach Boardwalk", cat:"beaches", dist:31.30, lat:36.8529, lng:-75.9780, addr:"Atlantic Ave, Virginia Beach", blurb:"A 3-mile oceanfront boardwalk and beach, free and open 24 hours — restaurants, shops, a fishing pier, and a dedicated bike path, about 30-40 minutes from the base depending on traffic.", hours:"Open 24 hours", phone:null, rating:4.6, reviewCount:0 },
  { id:"sandbridge-beach", name:"Sandbridge Beach", cat:"beaches", dist:39.45, lat:36.74611, lng:-75.94417, addr:"Sandbridge, Virginia Beach", blurb:"Known as \"Virginia's Outer Banks\" — a quieter, less crowded 4.5-mile stretch of oceanfront south of the main Virginia Beach strip, bordered by a national wildlife refuge. Genuinely worth the extra drive if you want fewer crowds.", hours:"Open 24 hours", phone:null, rating:4.7, reviewCount:0 },
  { id:"ocean-view-beach-park", name:"Ocean View Beach Park", cat:"beaches", dist:4.34, lat:36.958, lng:-76.263, addr:"100 W Ocean View Ave, Norfolk", blurb:"The closest beach to the base — a free Chesapeake Bay beach with a boardwalk, bandshell for live music, and good fishing piers. Less surf than the oceanfront, but genuinely convenient for an after-work swim.", hours:"Daily 6:00–19:30", phone:"+1 757-441-2345", rating:3.9, reviewCount:0 },

  // Historic Triangle Day Trips
  { id:"colonial-williamsburg", name:"Colonial Williamsburg", cat:"historic", dist:50.41, lat:37.2707, lng:-76.7075, addr:"101 Visitor Center Dr, Williamsburg", blurb:"America's largest living-history museum — an entire 18th-century colonial capital brought to life with costumed interpreters, historic trades, and taverns. Open 365 days a year, about an hour from the base.", hours:"Daily 9:30–17:00", phone:"+1 800-447-8679", rating:4.7, reviewCount:0 },
  { id:"yorktown-battlefield", name:"Yorktown Battlefield", cat:"historic", dist:37.27, lat:37.238441, lng:-76.516869, addr:"1000 Colonial Pkwy, Yorktown", blurb:"A free National Park Service site marking the final major battle of the American Revolution — walking trails through the actual siege lines and earthworks, with a visitor center exhibit on the 1781 siege.", hours:"Daily 9:00–17:00", phone:"+1 757-898-2410", rating:4.7, reviewCount:118 },
  { id:"west-freemason-historic-district", name:"West Freemason Historic District", cat:"historic", dist:10.61, lat:36.85222, lng:-76.29444, addr:"West Freemason St area, Norfolk", blurb:"Norfolk's oldest standing neighborhood and its very first historic district — tree-lined cobblestone streets, the city's oldest surviving granite curbs and cast iron fences, and houses dating to the 1790s. A genuinely worthwhile stroll right in the city, no drive required.", hours:"Open to the public — a residential district, best viewed on foot", phone:null, rating:4.6, reviewCount:0 },
  { id:"isle-of-wight-county-museum", name:"Isle of Wight County Museum", cat:"historic", dist:28.81, lat:36.98208721966359, lng:-76.63107886095914, addr:"103 Main St, Smithfield", blurb:"A genuinely charming small-town museum in historic Smithfield — home to the \"World's Oldest Ham\" (cured in 1902, featured in Ripley's Believe It or Not!), plus a turn-of-the-century country store and Civil War exhibits.", hours:"Mon–Sat 10:00–16:00 · Sun 12:00–16:00", phone:"+1 757-356-1223", rating:4.5, reviewCount:0 },

  // Shopping
  { id:"wards-corner-shopping-center", name:"Wards Corner Shopping Center", cat:"shopping", dist:6.36, lat:36.912, lng:-76.253, addr:"E Little Creek Rd & Granby St, Norfolk", blurb:"A historic Norfolk shopping hub currently undergoing major revitalization, anchored by a Harris Teeter with a Target under construction — worth checking for the mix of local and national retailers.", hours:"Varies by store", phone:null, rating:3.7, reviewCount:0 },

  // Outdoors & Kids
  { id:"norfolk-botanical-garden", name:"Norfolk Botanical Garden", cat:"outdoors", dist:10.44, lat:36.90278, lng:-76.20611, addr:"6700 Azalea Garden Rd, Norfolk", blurb:"A 175-acre garden with over 65 themed gardens and a 3-acre children's adventure garden — explore by tram, boat, or on foot, one of the largest azalea and camellia collections on the East Coast.", hours:"Daily 9:00–19:00", phone:"+1 757-441-5830", rating:4.7, reviewCount:0 },
  { id:"first-landing-state-park", name:"First Landing State Park", cat:"outdoors", dist:23.18, lat:36.918020, lng:-76.051547, addr:"2500 Shore Drive, Virginia Beach", blurb:"Virginia's most popular state park — 20 miles of trails through bald cypress swamps and maritime forest, plus a mile and a half of Chesapeake Bay beach frontage. Cabins and camping available.", hours:"Daily, dawn to dusk", phone:"+1 800-933-7275", rating:4.7, reviewCount:0 },
  { id:"chesapeake-city-park", name:"Chesapeake City Park", cat:"outdoors", dist:19.55, lat:36.777, lng:-76.253, addr:"900 City Park Dr, Chesapeake", blurb:"A 90-acre free city park with the award-winning Fun Forest playground, a 3/4-mile walking loop, a dog park, and an outdoor concert stage — genuinely nice for a family afternoon out.", hours:"Daily, dawn to dusk", phone:"+1 757-382-6411", rating:4.6, reviewCount:0 },
  { id:"northside-park-norfolk", name:"Northside Park", cat:"outdoors", dist:7.90, lat:36.900, lng:-76.243, addr:"8400 Tidewater Dr, Norfolk", blurb:"A genuinely well-loved city park along Broad Creek — walking trails, athletic fields, and open green space, popular with runners and dog walkers.", hours:"Daily, dawn to dusk", phone:null, rating:4.5, reviewCount:0 },

  // Shopping (2nd entry)
  { id:"lynnhaven-mall", name:"Lynnhaven Mall", cat:"shopping", dist:21.31, lat:36.822, lng:-76.128, addr:"701 Lynnhaven Pkwy, Virginia Beach", blurb:"The largest mall in Hampton Roads — 180 stores and 11 anchor tenants, a genuine full-day shopping option if Wards Corner doesn't have what you need.", hours:"Mon–Sat 10:00–21:00 · Sun 11:00–19:00", phone:null, rating:4.1, reviewCount:0 },
  { id:"norfolk-premium-outlets", name:"Norfolk Premium Outlets", cat:"shopping", dist:12.16, lat:36.8824775, lng:-76.1991834, addr:"1600 Premium Outlets Blvd, Norfolk", blurb:"An outlet shopping complex with 50+ discount stores — a genuinely convenient stop for brand-name deals without driving all the way to Williamsburg's outlets.", hours:"Mon–Sat 10:00–21:00 · Sun 11:00–19:00", phone:null, rating:4.0, reviewCount:0 },
  { id:"virginia-zoo", name:"Virginia Zoo", cat:"kids", dist:9.19, lat:36.8712, lng:-76.2681, addr:"3500 Granby St, Norfolk", blurb:"A well-loved AZA-accredited zoo dating back to 1901 — giraffes, rhinos, a petting zoo, and a train ride, genuinely great for a half-day with kids.", hours:"Daily 9:30–16:00", phone:"+1 757-441-2374", rating:4.5, reviewCount:274 },
  { id:"sky-zone-virginia-beach", name:"Sky Zone Virginia Beach", cat:"kids", dist:33.86, lat:36.771, lng:-75.999, addr:"1736 General Booth Blvd, Virginia Beach", blurb:"An indoor trampoline park with wall-to-wall jumping, dodgeball, and a foam pit — genuinely great for burning off energy on a rainy day, with birthday party packages available.", hours:"Mon–Thu 10:00–20:00 · Fri 10:00–22:00 · Sat 9:00–22:00 · Sun 10:00–19:00", phone:"+1 757-930-7155", rating:4.3, reviewCount:0 },
  { id:"mount-trashmore-kids-cove", name:"Kids Cove at Mount Trashmore Park", cat:"kids", dist:28.29, lat:36.816, lng:-76.037, addr:"310 Edwin Dr, Virginia Beach", blurb:"A genuinely massive, free, wheelchair-accessible playground on a former landfill turned 165-acre park — nearly 26,000 sq ft of slides, climbers, and a one-of-a-kind wheelchair swing, plus a skate park and two lakes nearby.", hours:"Daily 7:30–sunset", phone:null, rating:4.7, reviewCount:25 },

  // Attractions Around Hampton Roads — the base sits at the center of a genuinely
  // large metro area (Virginia Beach, Portsmouth, Newport News, Hampton, Chesapeake,
  // Suffolk), each with its own worthwhile things to do, not just Norfolk itself.
  { id:"virginia-aquarium", name:"Virginia Aquarium & Marine Science Center", cat:"attraction", dist:30.78, lat:36.8195, lng:-76.0025, addr:"717 General Booth Blvd, Virginia Beach", blurb:"Over 800,000 gallons of exhibits and 300+ species — sharks, sea turtles, seals, and a nature trail out over the marsh. A genuinely great full day out, with a military discount on admission.", hours:"Daily 9:00–17:00", phone:"+1 757-385-3474", rating:4.6, reviewCount:457 },
  { id:"mariners-museum-park", name:"The Mariners' Museum and Park", cat:"attraction", dist:19.86, lat:37.0550, lng:-76.4878, addr:"100 Museum Dr, Newport News", blurb:"One of the largest maritime museums in North America, home to the USS Monitor Center — and just $1 admission. Surrounded by a free 550-acre park with a 5-mile trail around Mariners' Lake.", hours:"Daily 9:00–17:00", phone:"+1 757-596-2222", rating:4.8, reviewCount:101 },
  { id:"virginia-air-space-center", name:"Virginia Air & Space Science Center", cat:"attraction", dist:9.11, lat:37.023944, lng:-76.344498, addr:"600 Settlers Landing Rd, Hampton", blurb:"The official visitor center for NASA's Langley Research Center — the Apollo 12 Command Module, a genuine moon rock, 30+ historic aircraft, and a 3D IMAX theater. One of only 12 official NASA visitor centers in the country.", hours:"Mon–Fri 10:00–17:00 · Sun 12:00–17:00 · Closed Sat", phone:"+1 757-727-0900", rating:4.5, reviewCount:0 },
  { id:"childrens-museum-of-virginia", name:"Children's Museum of Virginia", cat:"attraction", dist:12.48, lat:36.8349, lng:-76.2988, addr:"221 High St, Portsmouth", blurb:"The largest children's museum in the state, right in historic Olde Towne Portsmouth — a life-size tugboat, a real fire truck cab, a planetarium, and one of the East Coast's biggest antique toy and model train collections.", hours:"Tue–Sun 9:00–16:00 · Closed Mon", phone:"+1 757-393-5258", rating:4.5, reviewCount:154 },
  { id:"great-dismal-swamp", name:"Great Dismal Swamp National Wildlife Refuge", cat:"attraction", dist:42.30, lat:36.58333, lng:-76.45000, addr:"Refuge headquarters, Suffolk/Chesapeake", blurb:"112,000 acres of forested wetlands spanning Chesapeake and Suffolk, with 40+ miles of trails around Lake Drummond — a genuine stop on the Underground Railroad, and free to explore. Great for hiking, birding, and kayaking.", hours:"Trails: daily, sunrise–sunset · Office: Mon–Fri 8:00–16:00", phone:null, rating:4.6, reviewCount:0 },

  // Religious
  { id:"navsta-norfolk-chapel", name:"Naval Station Norfolk Chapel Complex", cat:"religious", dist:0.78, lat:36.94673, lng:-76.31858, addr:"1530 Gilbert St (just inside Gate 2), Norfolk", blurb:"An on-base, multi-faith chapel complex — Our Lady of Victory Chapel (Catholic), David Adams Memorial Chapel (Protestant), the Commodore Uriah P. Levy Chapel (the Navy's oldest Jewish chapel), and Masjid al Da'wah Mosque, all under one roof.", hours:"Catholic Mass Sun 09:30 & Wed 11:30 · Protestant Sun 10:30 · Jewish Shabbat Fri 11:45 · Islamic Prayers Fri 13:00", phone:"+1 757-444-7361", rating:4.5, reviewCount:0 },
  { id:"basilica-st-mary-norfolk", name:"Basilica of Saint Mary of the Immaculate Conception", cat:"religious", dist:11.37, lat:36.84694, lng:-76.28222, addr:"232 Chapel St, Norfolk", blurb:"A genuinely historic minor basilica downtown — the oldest Catholic parish in the Diocese of Richmond, known locally as the \"Mother Church of Tidewater Virginia,\" with striking Gothic Revival architecture dating to 1857.", hours:"Check parish office for current Mass times", phone:null, rating:4.7, reviewCount:0 },
  { id:"ohef-sholom-temple", name:"Ohef Sholom Temple", cat:"religious", dist:11.22, lat:36.847, lng:-76.291, addr:"530 Raleigh Ave, Norfolk", blurb:"A Reform synagogue that's served as Hampton Roads' leading Jewish congregation for over 150 years — \"A House of Prayer for All Peoples,\" with hybrid Friday evening and Saturday morning Shabbat services.", hours:"Office Mon–Thu 9:00–17:00 · Fri 9:00–16:00 · Closed Sat/Sun", phone:"+1 757-625-4295", rating:4.9, reviewCount:0 },

  // Community
  { id:"fleet-family-support-center", name:"Fleet & Family Support Center", cat:"community", dist:6.68, lat:36.887, lng:-76.303, addr:"7928 14th St, Bldg SDA-344, Norfolk", blurb:"A genuinely useful, free one-stop resource for military families — relocation help, deployment support, financial counseling, new parent support, and employment assistance, all in one place.", hours:"Mon–Fri 8:00–16:00", phone:"+1 757-444-2102", rating:4.4, reviewCount:0 },
  { id:"blocker-norfolk-ymca", name:"Blocker Norfolk Family YMCA", cat:"community", dist:10.32, lat:36.856, lng:-76.286, addr:"312 W Bute St, Norfolk", blurb:"A full-service downtown YMCA with a gym, pool, and fitness classes open to the whole family — financial assistance available for those who need it.", hours:"Mon–Thu 5:00–21:00 · Fri 5:00–20:00 · Sat 7:00–17:00 · Sun 13:00–17:00", phone:"+1 757-622-9622", rating:4.3, reviewCount:0 },
  { id:"slover-library", name:"Slover Library (Downtown Branch)", cat:"community", dist:11.11, lat:36.848, lng:-76.291, addr:"235 E Plume St, Norfolk", blurb:"A genuinely impressive free public library downtown — a youth learning center, digital media lab, and computer/internet access, all free with a library card.", hours:"Mon 10:00–18:00 · Tue–Thu 9:00–19:00 · Fri/Sat 9:00–17:00 · Closed Sun", phone:null, rating:4.7, reviewCount:0 },
  { id:"boys-girls-clubs-se-virginia", name:"Boys & Girls Clubs of Southeast Virginia", cat:"community", dist:9.84, lat:36.895, lng:-76.220, addr:"3415 Azalea Garden Rd, Norfolk", blurb:"An affordable after-school and summer program for youth — homework help, mentoring, sports, and enrichment activities in a safe, supervised setting.", hours:"Mon–Fri, after-school hours", phone:null, rating:4.2, reviewCount:0 },

  // Legal
  { id:"naval-legal-service-office", name:"Naval Legal Service Office Mid-Atlantic", cat:"legal", dist:0.46, lat:36.947, lng:-76.315, addr:"Bldg A-50, 9620 Maryland Ave, Naval Station Norfolk", blurb:"On-base legal assistance for service members and families — wills, powers of attorney, notary services, and general legal questions, on a walk-in basis.", hours:"Mon–Thu 07:45–11:45 & 12:45–15:45 · Fri 09:00–12:45", phone:"+1 757-341-4489", rating:3.9, reviewCount:0 },
  { id:"legal-aid-society-eastern-va", name:"Legal Aid Society of Eastern Virginia", cat:"legal", dist:10.01, lat:36.858, lng:-76.291, addr:"Norfolk (Community Support Team)", blurb:"A nonprofit law firm providing free civil legal representation to low-income Hampton Roads residents since 1966 — doesn't handle criminal, traffic, or immigration cases, but a genuinely valuable resource for other civil matters.", hours:"Intake: Mon,Tue,Thu,Fri 9:00–13:00", phone:"+1 757-827-5078", rating:4.0, reviewCount:0 },
  { id:"norfolk-portsmouth-bar-lrs", name:"Norfolk & Portsmouth Bar Association Lawyer Referral Service", cat:"legal", dist:11.13, lat:36.848, lng:-76.290, addr:"999 Waterside Dr Suite 1330, Norfolk", blurb:"A nonprofit referral service that matches you with a pre-screened local attorney for your specific legal issue — a 30-minute consultation for a modest flat fee, genuinely useful if you don't already know which lawyer to call.", hours:"Mon–Fri, business hours", phone:"+1 757-623-0132", rating:4.0, reviewCount:0 },

  // Tailoring & Dry Cleaning
  { id:"aj-alterations-cleaners", name:"A & J Alterations & Cleaners", cat:"tailor", dist:10.01, lat:36.858, lng:-76.291, addr:"4117 Granby St, Norfolk", blurb:"A genuinely well-regarded alterations and dry cleaning shop with real military experience — uniform patches, hems, and formalwear alterations done right.", hours:"Mon–Fri 9:00–18:00 · Sat 9:00–16:30 · Closed Sun", phone:"+1 757-625-3031", rating:4.5, reviewCount:12 },
  { id:"bethel-tailor-hampton", name:"Bethel Tailor", cat:"tailor", dist:9.22, lat:37.017, lng:-76.365, addr:"1114 Big Bethel Rd Ste 113, Hampton", blurb:"Alterations and dry cleaning with a real specialty in military uniforms, wedding dresses, and formalwear — women-owned, serving Hampton Roads for over 20 years.", hours:"Mon–Fri 9:30–18:00 · Sat 9:30–16:30 · Closed Sun", phone:"+1 757-827-3344", rating:4.6, reviewCount:29 },
  { id:"perfect-fit-alterations", name:"Perfect Fit Alterations", cat:"tailor", dist:20.38, lat:36.771, lng:-76.245, addr:"357 Johnstown Rd, Chesapeake", blurb:"A well-regarded seamstress shop handling everything from simple hems to major alterations on formalwear and wedding gowns — praised for careful work on delicate fabrics like lace.", hours:"Check store for current hours", phone:null, rating:4.5, reviewCount:26 },

  // Storage
  { id:"public-storage-w35th", name:"Public Storage (W 35th St)", cat:"storage", dist:7.19, lat:36.885, lng:-76.286, addr:"1090 W 35th St, Norfolk", blurb:"Conveniently located near Hampton Blvd and I-64 — a range of unit sizes, popular with military families needing flexible short-term storage around a move or deployment.", hours:"Office: Mon–Fri 9:30–18:00 · Sat 9:30–17:00 · Sun 11:00–17:00", phone:null, rating:3.6, reviewCount:0 },
  { id:"extra-space-storage-naval-base-rd", name:"Extra Space Storage (Naval Base Rd)", cat:"storage", dist:2.14, lat:36.930, lng:-76.298, addr:"301 Naval Base Rd, Norfolk", blurb:"Genuinely the closest storage option to the gates — drive-up and climate-controlled units, with a military discount commonly available for PCS moves and deployments.", hours:"Office hours vary — check current listing", phone:null, rating:3.7, reviewCount:0 },
  { id:"cubesmart-tidewater-dr", name:"CubeSmart Self Storage (Tidewater Dr)", cat:"storage", dist:5.67, lat:36.917, lng:-76.258, addr:"1108 Tidewater Dr, Norfolk", blurb:"A well-reviewed CubeSmart location with climate-controlled units and moving supplies on-site — open all 7 days.", hours:"Daily — hours vary, call ahead", phone:null, rating:5.0, reviewCount:0 },

  // Farmers Market
  { id:"riverview-village-farmers-market", name:"Riverview Village Day's Farmers' Market", cat:"farmers", dist:7.99, lat:36.87852, lng:-76.281973, addr:"3500 Granby St, Norfolk", blurb:"Described as the area's largest open-air farmers' market — 65+ vendors selling produce, honey, eggs, plants, and crafts, held twice monthly.", hours:"2nd & 4th Sundays, April–December, 11:00–16:00", phone:"+1 757-752-4316", rating:4.5, reviewCount:0 },
  { id:"ghent-farmers-market", name:"Ghent Farmer's Market", cat:"farmers", dist:8.00, lat:36.876, lng:-76.294, addr:"In front of Blair Middle School, 730 Spotswood Ave, Norfolk", blurb:"A smaller, weather-permitting neighborhood market right in Ghent — a nice complement to the bigger Riverview market if the dates don't line up.", hours:"1st & 3rd Fridays, April–September", phone:null, rating:4.3, reviewCount:0 },
  { id:"old-beach-farmers-market", name:"Old Beach Farmers Market", cat:"farmers", dist:31.37, lat:36.851, lng:-75.978, addr:"611 18th St, Virginia Beach", blurb:"A genuinely charming open-air market just blocks from the oceanfront — local produce, pasture-raised meats, and Virginia wines, with a real community feel.", hours:"Saturdays 9:00–12:00, mid-May–September (plus special Nov/Dec markets)", phone:"+1 757-428-5444", rating:4.5, reviewCount:26 },

  // More Museums & Attractions
  { id:"casemate-museum-fort-monroe", name:"Casemate Museum at Fort Monroe", cat:"museum", dist:6.24, lat:37.0028, lng:-76.3057, addr:"20 Bernard Rd, Fort Monroe, Hampton", blurb:"Free museum inside America's largest stone fort — walk through the actual casemates, including the cell where Confederate president Jefferson Davis was imprisoned. Requires a free timed-entry ticket from the Visitor & Education Center.", hours:"Wed–Sun 10:00–16:00 · Closed Mon/Tue", phone:"+1 757-690-8181", rating:4.6, reviewCount:38 },
  { id:"great-bridge-battlefield-museum", name:"Great Bridge Battlefield & Waterways Museum", cat:"museum", dist:25.35, lat:36.727, lng:-76.234, addr:"1289 Battlefield Blvd S, Chesapeake", blurb:"Marks the site of the first American victory of the Revolutionary War — 8 galleries, a historic interpretive trail, and the story of William \"Billy\" Flora, a free Black man who became a hero of the battle. Discounted admission for military and veterans.", hours:"Tue–Sat 10:00–17:00 · Sun 12:00–17:00 · Closed Mon", phone:null, rating:4.7, reviewCount:0 },
  { id:"hermitage-museum-gardens", name:"The Hermitage Museum & Gardens", cat:"museum", dist:6.84, lat:36.898, lng:-76.263, addr:"7637 North Shore Rd, Norfolk", blurb:"A free early-20th-century Arts-and-Crafts estate on the Lafayette River — a nationally recognized art collection spanning 5,000 years, plus 12 acres of gardens and working artist studios.", hours:"Tue–Sun 10:00–17:00 · Closed Mon", phone:null, rating:4.7, reviewCount:0 },
  { id:"chrysler-museum-glass-studio", name:"Chrysler Museum Perry Glass Studio", cat:"museum", dist:10.80, lat:36.851, lng:-76.290, addr:"745 Duke St, Norfolk", blurb:"Watch live glassblowing, flameworking, and neon-making at the only facility of its kind in the Mid-Atlantic — free demonstrations daily, plus hands-on classes for aspiring artists. A genuinely unique companion to the main Chrysler Museum.", hours:"Tue–Sat 10:00–17:00 · Sun 12:00–17:00 · Closed Mon", phone:null, rating:4.8, reviewCount:0 },
  { id:"macarthur-memorial", name:"MacArthur Memorial", cat:"museum", dist:11.13, lat:36.848, lng:-76.290, addr:"198 Bank St, Norfolk", blurb:"A free museum and the final resting place of General Douglas MacArthur — exhibits spanning WWI, WWII, and the Korean War, a genuine must for military history buffs.", hours:"Tue–Sat 10:00–17:00 · Closed Mon/Sun", phone:"+1 757-441-2965", rating:4.7, reviewCount:39 },

  // Car Dealers
  { id:"priority-ford-norfolk", name:"Priority Ford", cat:"cars", dist:11.01, lat:36.885, lng:-76.213, addr:"3420 N Military Hwy, Norfolk", blurb:"A full-service Ford dealership with new and used inventory, plus a service and parts department for routine maintenance and repairs.", hours:"Mon–Fri 9:00–20:00 · Sat 9:00–18:00 · Sun 12:00–17:00", phone:"+1 757-255-8935", rating:4.2, reviewCount:180 },
  { id:"carmax-virginia-beach", name:"CarMax (Virginia Beach)", cat:"cars", dist:27.62, lat:36.812, lng:-76.049, addr:"3801 Bonney Rd, Virginia Beach", blurb:"No-haggle used car pricing with a huge inventory — genuinely convenient if you'd rather skip the traditional dealership negotiation entirely.", hours:"Mon–Fri 10:00–21:00 · Sat 9:00–21:00 · Sun 12:00–19:00", phone:null, rating:4.0, reviewCount:163 },
  { id:"priority-toyota-chesapeake", name:"Priority Toyota Chesapeake", cat:"cars", dist:19.75, lat:36.782, lng:-76.227, addr:"1800 Greenbrier Pkwy, Chesapeake", blurb:"A large Toyota dealership with new, used, and certified pre-owned inventory, plus a Master Toyota Technician service department for maintenance and repairs.", hours:"Check dealership for current hours", phone:null, rating:4.1, reviewCount:0 },
  { id:"hall-toyota-virginia-beach", name:"Hall Toyota Virginia Beach", cat:"cars", dist:27.12, lat:36.848, lng:-76.031, addr:"1877 Laskin Rd, Virginia Beach", blurb:"A large Toyota dealership with a genuine military rewards perk — 500 bonus Hall Rewards points on every service visit for military members, plus new, used, and certified pre-owned inventory.", hours:"Check dealership for current hours", phone:"+1 757-271-9725", rating:4.0, reviewCount:0 },

  // Education
  { id:"tcc-norfolk-campus", name:"Tidewater Community College – Norfolk Campus", cat:"education", dist:10.80, lat:36.851, lng:-76.290, addr:"300 Granby St, Norfolk", blurb:"An affordable, accessible option for continuing education or a degree while stationed here — commonly used with Tuition Assistance, and one of four TCC campuses across Hampton Roads.", hours:"Mon–Tue 8:30–18:30 · Wed–Fri 8:30–17:00", phone:"+1 757-822-1110", rating:3.9, reviewCount:0 },
  { id:"odu-continuing-education", name:"Old Dominion University — Continuing Education", cat:"education", dist:6.66, lat:36.887, lng:-76.305, addr:"1262 W 43rd St, Norfolk", blurb:"Certificate and non-credit programs geared toward career advancement — Project Management, Cybersecurity, PMP Exam prep, and more, with flexible online formats that work well around a duty schedule.", hours:"Mon–Fri 8:00–17:00", phone:"+1 757-683-5650", rating:4.1, reviewCount:0 },
  { id:"regent-university", name:"Regent University", cat:"education", dist:16.19, lat:36.848, lng:-76.176, addr:"1000 Regent University Dr, Virginia Beach", blurb:"A genuinely military-friendly Christian university offering 150+ degree programs, associate through doctoral, both online and on its 70-acre campus.", hours:"Mon–Fri 8:00–18:00 · Closed Sat/Sun", phone:"+1 757-352-4127", rating:4.3, reviewCount:46 },

  // Notary & Shipping
  { id:"ups-store-ghent", name:"The UPS Store (Ghent)", cat:"notary", dist:8.00, lat:36.876, lng:-76.294, addr:"520 W 21st St, Norfolk", blurb:"Locally owned and operated — shipping, printing, mailbox rental, and notary services, right in the heart of Ghent next to Starbucks.", hours:"Open 7 days — check store for daily hours", phone:"+1 757-626-1766", rating:4.3, reviewCount:0 },
  { id:"fedex-office-va-beach-blvd", name:"FedEx Office Print & Ship Center", cat:"notary", dist:15.19, lat:36.858, lng:-76.180, addr:"5957 E Virginia Beach Blvd, Norfolk", blurb:"Shipping, printing, and online notary in one stop — also handles passport photos and Amazon returns, genuinely convenient for knocking out several errands at once.", hours:"Mon–Fri 8:00–19:00 · Sat 9:00–18:00 · Sun 12:00–18:00", phone:null, rating:3.9, reviewCount:0 },
  { id:"ups-store-tidewater-dr", name:"The UPS Store (Tidewater Dr)", cat:"notary", dist:5.67, lat:36.917, lng:-76.258, addr:"7870 Tidewater Dr Ste 206, Norfolk", blurb:"A second locally owned UPS Store location, at the corner of Tidewater & Little Creek Road — packing, shipping, printing, and notary services.", hours:"Mon–Fri 8:30–19:00 · Sat 9:00–15:00 · Closed Sun", phone:"+1 757-587-8771", rating:4.0, reviewCount:0 },

  // Bars
  { id:"the-ghent-rooftop-bar", name:"The Ghent Rooftop Bar", cat:"bars", dist:8.00, lat:36.876, lng:-76.294, addr:"319 W 21st St Suite A, Norfolk", blurb:"A genuinely fun, self-pour taphouse and rooftop lounge — activate a pour card and serve yourself beer, wine, and cocktails at your own pace, with fire pits and heaters for cooler nights.", hours:"Wed–Fri 17:00–22:00 · Sat 12:00–22:00 · Sun 12:00–21:00 · Closed Mon/Tue", phone:"+1 757-647-4820", rating:4.4, reviewCount:72 },
  { id:"elation-brewing", name:"Elation Brewing", cat:"bars", dist:7.41, lat:36.898, lng:-76.253, addr:"5104 Colley Ave, Norfolk", blurb:"Norfolk's own community brewpub in Larchmont — flagship and rotating craft beers, wood-fired Bakehouse pizza, and regular live local music.", hours:"Mon–Wed,Sun 12:00–21:00 · Thu–Sat 12:00–22:00", phone:"+1 757-452-6584", rating:4.6, reviewCount:120 },
  { id:"benchtop-brewing", name:"Benchtop Brewing Company", cat:"bars", dist:10.16, lat:36.858, lng:-76.283, addr:"1129 Boissevain Ave, Norfolk", blurb:"An innovative craft brewery in the Chelsea neighborhood — hop-forward ales, farmhouse ales, and adventurous sour/mixed-fermentation beers, with an on-site kitchen serving food Tuesday through Sunday.", hours:"Mon–Thu 15:00–21:00 · Fri/Sat 12:00–22:00 · Sun 12:00–19:00", phone:"+1 757-321-9482", rating:4.5, reviewCount:82 },

  // Phone & Internet
  { id:"att-store-ghent", name:"AT&T Store (Ghent)", cat:"phone", dist:8.00, lat:36.876, lng:-76.294, addr:"1304 Colley Ave, Norfolk", blurb:"Phones, tablets, accessories, and AT&T Home Internet — a straightforward stop for a new line, a device upgrade, or setting up service after a move.", hours:"Mon–Sat 10:00–20:00 · Sun 11:00–18:00", phone:"+1 757-625-1122", rating:4.2, reviewCount:187 },
  { id:"tmobile-wards-corner", name:"T-Mobile (Wards Corner)", cat:"phone", dist:6.36, lat:36.912, lng:-76.253, addr:"140 E Little Creek Rd, Norfolk", blurb:"A T-Mobile neighborhood store right at Wards Corner — phones, plans, and a military discount program worth asking about when setting up new service.", hours:"Check store for current hours", phone:"+1 757-583-5670", rating:4.0, reviewCount:0 },
  { id:"verizon-little-creek", name:"Verizon (E Little Creek Rd)", cat:"phone", dist:6.75, lat:36.918, lng:-76.243, addr:"725 E Little Creek Rd Ste 511, Norfolk", blurb:"A full-service Verizon store — phones, tablets, 5G home internet, and device trade-ins, with extended hours seven days a week.", hours:"Mon–Sat 10:00–20:00 · Sun 11:00–18:00", phone:"+1 757-372-4649", rating:3.8, reviewCount:0 },

  // Tattoo Shops
  { id:"colley-ave-tattoo", name:"Colley Ave Tattoo", cat:"tattoo", dist:7.41, lat:36.898, lng:-76.253, addr:"4701 Colley Ave, Norfolk", blurb:"A classic-style street shop specializing in traditional, blackwork, and Japanese tattooing — walk-ins welcome when an artist has an opening, no piercings.", hours:"Mon–Sat 11:00–20:00 · Closed Sun", phone:"+1 757-340-0008", rating:4.7, reviewCount:0 },
  { id:"otzi-tattoo-agency", name:"Otzi Tattoo Agency", cat:"tattoo", dist:10.16, lat:36.858, lng:-76.283, addr:"1130 Boissevain Ave, Norfolk", blurb:"An award-winning custom tattoo studio in the Chelsea District with 20 years of experience — specializing in realism, fine line, and cover-ups, with a strong reputation for its artists' range.", hours:"Tue–Sat 10:00–18:00 · Closed Sun/Mon", phone:"+1 757-502-8666", rating:4.8, reviewCount:0 },

  // Furniture
  { id:"grand-furniture-norfolk", name:"Grand Furniture", cat:"furniture", dist:7.19, lat:36.917, lng:-76.238, addr:"836 E Little Creek Rd, Norfolk", blurb:"A Hampton Roads furniture chain dating back to 1947 — living room, bedroom, and dining furniture plus mattresses, with financing options for those buying on a budget.", hours:"Mon,Tue,Thu 11:00–19:30 · Wed 10:45–19:30 · Fri/Sat 10:00–20:00 · Sun 11:00–19:00", phone:null, rating:3.8, reviewCount:24 },
  { id:"american-freight-furniture", name:"American Freight Furniture & Mattress", cat:"furniture", dist:15.19, lat:36.858, lng:-76.180, addr:"6359 E Virginia Beach Blvd, Norfolk", blurb:"A warehouse-style furniture and mattress store with everyday low prices — in-stock, ready-to-take-home items and flexible financing, without the showroom markup.", hours:"Mon–Sat 10:00–20:00 · Sun 12:00–18:00", phone:"+1 757-461-4111", rating:3.5, reviewCount:18 },

  // Recreation
  { id:"pierside-entertainment-center", name:"Pierside Entertainment Center", cat:"rec", dist:0.20, lat:36.945, lng:-76.310, addr:"B Ave, Bldg CEP-127, Naval Station Norfolk", blurb:"The on-base MWR bowling and entertainment center — bowling, an arcade, pool tables, a snack bar, and regular happy-hour game specials, right on base.", hours:"Mon–Thu 10:00–22:00 · Fri 10:00–24:00 · Sat 12:00–24:00 · Sun 13:00–19:00", phone:"+1 757-445-0646", rating:3.9, reviewCount:17 },
  { id:"the-norva", name:"The NorVa", cat:"rec", dist:10.91, lat:36.850, lng:-76.290, addr:"317 Monticello Ave, Norfolk", blurb:"A genuinely historic 1,450-capacity concert venue downtown, in a restored 1922 theater — a great mid-size stop for touring bands and comedians.", hours:"Box office and show hours vary by event", phone:null, rating:4.6, reviewCount:0 },

  // Base Services
  { id:"great-clips-odu", name:"Great Clips (ODU)", cat:"services", dist:8.00, lat:36.876, lng:-76.294, addr:"2000 Colonial Ave Ste 11, Norfolk", blurb:"A reliable, no-appointment-needed haircut chain — check in online to skip the wait, good for a quick trim between duty days.", hours:"Mon–Fri 9:00–21:00 · Sat 9:00–19:00", phone:"+1 757-440-8611", rating:4.0, reviewCount:23 },
  { id:"soaps-n-suds-colley", name:"Soaps N Suds Laundromat & Car Wash", cat:"services", dist:9.99, lat:36.858, lng:-76.293, addr:"2515 Colley Ave, Norfolk", blurb:"A clean, card-operated laundromat with a 24/7 brushless car wash on-site — large-capacity washers for comforters, plus off-street parking.", hours:"Daily, hours vary — car wash open 24/7", phone:"+1 757-313-0515", rating:4.0, reviewCount:0 },
  { id:"advance-auto-parts-va-beach-blvd", name:"Advance Auto Parts (E Virginia Beach Blvd)", cat:"services", dist:15.19, lat:36.858, lng:-76.180, addr:"5741 E Virginia Beach Blvd, Norfolk", blurb:"A full auto parts retailer with genuinely useful free services — battery testing and installation, engine code scanning, and wiper installation, all at no charge with purchase.", hours:"Mon–Sat 7:30–21:00 · Sun 8:00–20:00", phone:"+1 757-383-7864", rating:3.9, reviewCount:0 },

  // Recreation (2nd batch)
  { id:"commodore-theatre-portsmouth", name:"Commodore Theatre", cat:"rec", dist:12.25, lat:36.837, lng:-76.298, addr:"421 High St, Portsmouth", blurb:"A genuinely unique dinner-and-a-movie experience — a restored 1945 Art Deco theater where you order food and drinks by phone right from your table while watching first-run films.", hours:"Wed,Sat,Sun 12:45–19:00 · Mon,Tue,Thu 17:45–19:00 · Fri 17:30–19:00", phone:"+1 757-393-6962", rating:4.5, reviewCount:107 },
  { id:"attucks-theatre", name:"Attucks Theatre", cat:"rec", dist:10.42, lat:36.85639, lng:-76.27917, addr:"1010 Church St, Norfolk", blurb:"A genuinely remarkable National Historic Landmark — the oldest surviving theater in the country fully financed, designed, and built by African Americans, opened in 1919 as the \"Apollo of the South.\" Still hosts concerts, comedy, and plays today.", hours:"Box office opens 1 hour before showtime", phone:null, rating:4.7, reviewCount:0 },
];

const catLabels = { restaurant:"Restaurant", grocery:"Grocery", attraction:"Attraction", auto:"Auto", health:"Health", banking:"Banking", housing:"Housing", pets:"Pet Services", fitness:"Fitness", religious:"Religious", shopping:"Shopping", storage:"Storage", museum:"Museum", outdoors:"Outdoors", kids:"Kids", farmers:"Farmers Market", phone:"Phone/Internet", cars:"Car Dealer", tailor:"Tailoring", furniture:"Furniture", legal:"Legal", education:"Education", schools:"Schools", community:"Community", bars:"Bar", services:"Base Services", rec:"Recreation", tattoo:"Tattoo Shop", notary:"Notary/Shipping", beaches:"Beaches", historic:"Historic Triangle Day Trips" };
